# Generated by Django 4.2.2 on 2023-07-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='despacho',
            fields=[
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('dpto', models.CharField(max_length=15)),
                ('fechaEntrega', models.DateField()),
                ('ID_despacho', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('ID_pedido', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
