from django.urls import path
from . import views

urlpatterns = [
    path("signup", views.signup, name="signup"),
    path("index", views.index, name="index"),
    path("crud", views.crud, name="crud"),
    path("userAdd", views.userAdd, name="userAdd"),
    path("userDel/ <str:pk>", views.userDel, name="userDel"),
    path("userEdit/ <str:pk>", views.userEdit, name="userEdit"),
    path("userUpdate", views.userUpdate, name="userUpdate"),
    path("formAdd", views.formAdd, name="formAdd"),
    path("juegos", views.juegos, name="juegos"),
    path("crudTipo", views.crudTipo, name="crudTipo"),
    path("tipoAdd", views.tipoAdd, name="tipoAdd"),
    path("tipoDel/ <str:pk>", views.tipoDel, name="tipoDel"),
    path("tipoEdit/ <str:pk>", views.tipoEdit, name="tipoEdit"),
    path("", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("accesorios", views.accesorios, name="accesorios"),
    path("carrito", views.carrito, name="carrito"),
    path("estampados", views.estampados, name="estampados"),
    path("mpa1", views.mpa1, name="mpa1"),
    path("mpa2", views.mpa2, name="mpa2"),
    path("mpa3", views.mpa3, name="mpa3"),
    path("mpa4", views.mpa4, name="mpa4"),
    path("mpa5", views.mpa5, name="mpa5"),
    path("mpa6", views.mpa6, name="mpa6"),
    path("mpe1", views.mpe1, name="mpe1"),
    path("mpe2", views.mpe2, name="mpe2"),
    path("mpe3", views.mpe3, name="mpe3"),
    path("mpe4", views.mpe4, name="mpe4"),
    path("mpe5", views.mpe5, name="mpe5"),
    path("mpp1", views.mpp1, name="mpp1"),
    path("mpp2", views.mpp2, name="mpp2"),
    path("mpp3", views.mpp3, name="mpp3"),
    path("mpp4", views.mpp4, name="mpp4"),
    path("mpp5", views.mpp5, name="mpp5"),
    path("mpp6", views.mpp6, name="mpp6"),
    path("mpv1", views.mpv1, name="mpv1"),
    path("mpv2", views.mpv2, name="mpv2"),
    path("mpv3", views.mpv3, name="mpv3"),
    path("mpv4", views.mpv4, name="mpv4"),
    path('registro', views.registro, name='registro'),
    path("papeleria", views.papeleria, name="papeleria"),
    path("velas", views.velas, name="velas"),
]
